### ISSUE TITLE
Lots of "fatal error ... something.cppmap not found"

### ISSUE THREAD

**Issue by HappyCerberus** [hedronvision/bazel-compile-commands-extractor#83]
This does not seem to cause issues, but when I run the command to generate the compilation database, I get a lot of these errors (several pages).

Since this isn't mentioned in the documentation, I'm just curious if this is expected.

**Comment by cpsauer** [comment]
Hey! Thanks for writing in. Definitely unexpected--and not something I've seen yet.

Any chance I could get some more details on the error messages? Like maybe copy some in so I can see? Any idea what flags might be causing them--or any other error messages?

If you run a build and then rerun, do they go away? (making sure that the build and extraction are done with the same flags.

**Comment by HappyCerberus** [comment]
Here is the repo. If you open it in VSCode, it will auto-build a Docker image with a reproducible environment (otherwise you can also use the `.devcontainer/Dockerfile`).

https://github.com/HappyCerberus/meetingcpp22-bazel

It does go away on subsequent runs.

Note that the compilation error is expected, the repository has examples that deliberately do not compile:

```
root@cbdd97d8ceb1:/workspaces/meetingcpp22-bazel# bazel run @hedron_compile_commands//:refresh_all
Starting local Bazel server and connecting to it...
INFO: Analyzed target @hedron_compile_commands//:refresh_all (67 packages loaded, 522 targets configured).
INFO: Found 1 target...
Target @hedron_compile_commands//:refresh_all up-to-date:
  bazel-bin/external/hedron_compile_commands/refresh_all.py
  bazel-bin/external/hedron_compile_commands/refresh_all
INFO: Elapsed time: 5.036s, Critical Path: 0.03s
INFO: 6 processes: 6 internal.
INFO: Build completed successfully, 6 total actions
INFO: Running command line: bazel-bin/external/hedron_compile_commands/refresh
INFO: Build completed successfully, 6 total actions
>>> Analyzing commands used in @//...
>>> While locating the headers you use, we encountered a compiler warning or error.
    No need to worry; your code doesn't have to compile for this tool to work.
    However, we'll still print the errors and warnings in case they're helpful for you in fixing them.
    If the errors are about missing files that Bazel should generate:
        You might want to run a build of your code with --keep_going.
        That way, everything possible is generated, browsable and indexed for autocomplete.
    But, if you have *already* built your code successfully:
        Please make sure you're supplying this tool with the same flags you use to build.
        You can either use a refresh_compile_commands rule or the special -- syntax. Please see the README.
        [Supplying flags normally won't work. That just causes this tool to be built with those flags.]
    Continuing gracefully...
fatal error: module map file 'bazel-out/k8-fastbuild/bin/structured/greeter/greet.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/structured/hello_transitive.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/cache/cache_test.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/structured/hello.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/artefacts/custom_command.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/testing/binary.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/hello_world/hello.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/testing/library.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/platforms/library.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/wasm/main.cppmap' not found
1 error generated.
python3: can't open file '/workspaces/meetingcpp22-bazel//emscripten/emcc.py': [Errno 2] No such file or directory
fatal error: module map file 'bazel-out/k8-fastbuild/bin/testing/library_catch_test.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/hello_world/other_hello/other_hello.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2_main.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/testing/data_test.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/platforms/multi_platform.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest_main.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/cache/with_deps_test.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/structured/hello_private.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/sanitizers/use_after_free.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/cpp/runfiles/runfiles.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/testing/library_test.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/platforms/platform_linux.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/structured/greeter/format.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/googletest~1.11.0/gtest.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/src/tools/launcher/launcher.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-opt-exec-2B5CBBC6/bin/external/bazel_tools/src/tools/launcher/launcher.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
fatal error: module map file 'bazel-out/k8-fastbuild/bin/external/com_github_catchorg_catch2/catch2.cppmap' not found
1 error generated.
>>> Finished extracting commands for @//...
```

**Comment by HappyCerberus** [comment]
I should also note that this is for a conference talk so it's a combination of pre-release Bazel + plenty of features turned on (therefore can totally be a Bazel bug).

**Comment by cpsauer** [comment]
Thanks! Honored to be included in the code for your talk. Thanks for helping teach people! We use Bazel rolling, too.

I'm think I know what is causing this and how to fix it.
My hypothesis:
- `--features=layering_check` causes these module maps to be built as part of its checks (modules otherwise not really being supported by bazel, which is why we haven't seen these before)
- The module maps haven't yet been generated at the time you ran--hence the errors. Our caching silences the issue on future runs.

To test: Could I ask you to `rm bazel-out/**/*.hedron.compile-commands.headers` (wiping out our caches) and then remove `--features=layering_check`, and make sure it works? 

If so, I'll fix this problem by automatically toggling off that feature while  analyze Bazel's action graph, just like we do for param files on Windows.

**Comment by cpsauer** [comment]
Actually, to save a round trip, I've just pushed the change that I think will fix the problem.
[Sorry to drop off on you last night. We're in very different timezones. I think that makes it even cooler that we're collaborating!]

Could I still have you run the test above, still rm'ing, but grabbing the latest commit of this tool rather than manually removing layering_check from your bazelrc? That'll tell us whether the fix worked!

Also, to satisfy my curiosity, could I ask you to also confirm (before doing the checks above) that (1) the module map files do indeed not exist (bazel cleaning them away if they do) and (2) when they don't exist, checking whether or not clangd shows errors in the editor about the missing module maps? They'd probably show up under a red squiggly at the very first character of the file and in the error panel. This is super helpful because it'd inform future decisions around how we support modules.

**Comment by HappyCerberus** [comment]
Perfect, thank you.

Your intuition was indeed correct, I can confirm that manual delete + disabling layering fixed it and the updated version does as well.

I'm still seeing one more unexpected error if you are interested in digging further :-D

```
python3: can't open file '/workspaces/meetingcpp22-bazel//emscripten/emcc.py': [Errno 2] No such file or directory
```

**Comment by cpsauer** [comment]
Great! Glad we could get that fixed for you. Thanks for reporting and checking.

Did you get a chance to check whether the previous error showed up in the red squiggly – before the fix?

I'll take a look at the other one when I get a chance. It looks emscripten specific. As always, any more errors or context would be handy. Any idea how that file is normally created or where it actually is? My guess is that that's the compiler, and we're trying to invoke it to get headers, but that the compiler indeed does not exist yet.

**Comment by cpsauer** [comment]
Have reproduced this new issue. let me see if I can figure out what's going on :)

**Comment by cpsauer** [comment]
Oh, boy, okay, something slightly different. What's happening is that the emscripten wrapper is dependent on environment variables that [this bazel bug](https://github.com/bazelbuild/bazel/issues/12852) stops us from getting.

**Comment by cpsauer** [comment]
Hey, @HappyCerberus. I worked on this a bit more, and I think I've now gotten things working for emscripten. (you were the first to ask!)

It took a bit of doing, since emscripten is set up to be *so* reliant on all its environment variables...and that Bazel bug means we'd have to reconstruct them all. So instead I took the approach of instead calling clang or gcc for header extraction.

I think that'll make things work (so I'm going to optimistically close), but I'd love it if you'd `bazel clean` and then give the latest a whirl for me. If you have any more problems, please just let me know, and I'll open this right back up.

Cheers,
Chris

**Comment by HappyCerberus** [comment]
This fell through the cracks on my side, but I can finally confirm that this is fixed.

Thanks again!

**Comment by cpsauer** [comment]
Great! You're very welcome. Thanks for getting back to me.

Happy coding!
